"""Initialize User Entity...

Revision ID: 585aab502d99
Revises: 5a3a3ca08be1
Create Date: 2023-08-20 22:58:29.699628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '585aab502d99'
down_revision: Union[str, None] = '5a3a3ca08be1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
