"""Initialize User Entity...

Revision ID: 5d516d475ff4
Revises: a0066e4a6527
Create Date: 2023-08-20 22:31:33.255329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d516d475ff4'
down_revision: Union[str, None] = 'a0066e4a6527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
