"""Initialize roadmap, roadmap node, user entity

Revision ID: f4cf9684791f
Revises: 64697487e843
Create Date: 2023-08-29 19:11:30.885292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4cf9684791f'
down_revision: Union[str, None] = '64697487e843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmap',
    sa.Column('roadmap_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('roadmap_id')
    )
    op.create_table('roadmap_node',
    sa.Column('node_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('roadmap_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['roadmap_node.node_id'], ),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmap.roadmap_id'], ),
    sa.PrimaryKeyConstraint('node_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roadmap_node')
    op.drop_table('roadmap')
    # ### end Alembic commands ###
